# Generated by Django 3.2.2 on 2021-07-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210718_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, choices=[('CZ', 'Czech'), ('ENG', 'English')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
