# Generated by Django 3.2.2 on 2021-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210719_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, choices=[('cz', 'Czech'), ('eng', 'English')], max_length=3, null=True),
        ),
    ]
