# Generated by Django 3.2.2 on 2021-08-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(blank=True, null=True, upload_to='images/profile/gallery')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='profile',
            name='gallery_images',
            field=models.ManyToManyField(related_name='profile_gallery', to='blog.GalleryImg'),
        ),
    ]
