# Generated by Django 3.2.2 on 2021-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210810_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimg',
            name='img_text',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
