# Generated by Django 3.2.2 on 2021-08-21 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_galleryimg_img_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimg',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='galleryimg',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
