# Generated by Django 3.2.2 on 2021-08-21 19:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210821_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimg',
            name='gallery_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='images/profile/gallery'),
        ),
    ]
