# Generated by Django 3.2.2 on 2021-08-22 18:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_galleryimg_gallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimg',
            name='gallery_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1600, 900], upload_to='images/profile/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='images/profile'),
        ),
    ]
