# Generated by Django 3.2.2 on 2021-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210822_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='profile_gallery', to='blog.GalleryImg'),
        ),
    ]
